return {
  make = "Meris",
  model = "Hedra",
  control = {
    [4] = "Expression Pedal",
    [9] = "Half Speed Enable",
    [14] = "Bypass",
    [15] = "Tempo",
    [16] = "Key",
    [17] = "Micro Tune",
    [18] = "Mix",
    [19] = "Pitch 1",
    [20] = "Pitch 2",
    [21] = "Pitch 3",
    [22] = "Scale Type",
    [23] = "Pitch Correction + Glide",
    [24] = "Feedback",
    [25] = "Time Division 1",
    [26] = "Time Division 2",
    [27] = "Time Division 3",
    [28] = "Tap",
    [29] = "Delay Mode",
    [30] = "Pitch Control Smoothing",
    [31] = "Volume Swell Enable"
  },
  program = {
    [1] = "Series Sequence",
    [2] = "Pitch Echo",
    [3] = "Micro Fall",
    [4] = "Micro Chorus",
    [5] = "Hard Tune Triplet",
    [6] = "Stereo Octave",
    [7] = "Carle Place Shred",
    [8] = "Expression Steel",
    [9] = "Tick Tock",
    [10] = "Layers",
    [11] = "Expression Shift",
    [12] = "Pentatonic Correct",
    [13] = "Infinite Arcade",
    [14] = "Mirror Glide",
    [15] = "Bumble Trail",
    [16] = "Folding Intervals"
  }
}